name: NPM Publish
on:
  workflow_call:
    inputs:
      project_key:
        required: true
        type: string
  pull_request:
  push:
    branches: [ $default-branch ]

env:
  SONAR_ORG: flexbase
  SONAR_PROJECT_KEY: ${{ inputs.project_key }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
    - name: Retrieve build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist

    - name: Publish
      uses: actions/setup-node@v3
      with:
        registry-url: 'https://registry.npmjs.org'
      run: yarn publish
