name: Build
on:
  workflow_call:
    inputs:
      build_artifact_folder:
        required: false
        type: string
        default: 'dist'
      build_artifact_name:
        required: false
        type: string
        default: 'dist'
      package_manager:
        required: false
        type: string
        default: 'yarn'
      build_command:
        required: false
        type: string
        default: 'build'
      lint_command:
        required: false
        type: string
        default: 'lint'
      test_command:
        required: false
        type: string
        default: 'test'
      version_command:
        required: false
        type: string
        default: 'semantic-release'
      node_version:
        required: false
        type: string
        default: 'latest'
      packr_command:
        required: false
        type: string
        default: ''
      coverage_artifact_folder:
        required: false
        type: string
        default: 'coverage/lcov.info'
      coverage_artifact_name:
        required: false
        type: string
        default: 'code-coverage-report'

jobs:
  labeler:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compile:
    runs-on: ubuntu-latest
    env:
      CLI_INSTALL:
      CLI_BUILD:
      CLI_LINT:
      CYPRESS_BIN_PATH: '~/.cache/Cypress'
    outputs:
      cypress_bin_path: ${{ env.CYPRESS_BIN_PATH }}
    steps:
      - name: Create environment variables for yarn commands
        if: inputs.package_manager == 'yarn'
        run: |
          echo "CLI_INSTALL=yarn install --frozen-lockfile" >> $GITHUB_ENV
          echo "CLI_BUILD=yarn ${{ inputs.build_command }}" >> $GITHUB_ENV
          echo "CLI_LINT=yarn ${{ inputs.lint_command }}" >> $GITHUB_ENV
          echo "CLI_TEST_UNIT=yarn ${{ inputs.test_unit_command }}" >> $GITHUB_ENV
          echo "CLI_PACKR=yarn ${{ inputs.packr_command }}" >> $GITHUB_ENV
          echo "CLI_VERSION=yarn ${{ inputs.version_command }}" >> $GITHUB_ENV

      - name: Create environment variables for npm commands
        if: inputs.package_manager == 'npm'
        run: |
          echo "CLI_INSTALL=npm ci" >> $GITHUB_ENV
          echo "CLI_BUILD=npm run ${{ inputs.build_command }}" >> $GITHUB_ENV
          echo "CLI_LINT=npm run ${{ inputs.lint_command }}" >> $GITHUB_ENV
          echo "CLI_TEST_UNIT=npm run ${{ inputs.test_unit_command }}" >> $GITHUB_ENV
          echo "CLI_PACKR=npm run ${{ inputs.packr_command }}" >> $GITHUB_ENV
          echo "CLI_VERSION=npm run ${{ inputs.version_command }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: ${{ inputs.package_manager }}

      - name: Configure github internal package repo access
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=$PACKAGE_TOKEN" > .npmrc
          echo "@flexbase-eng:registry=https://npm.pkg.github.com" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Install dependencies
        run: ${{ env.CLI_INSTALL }}

      - name: Compile
        run: ${{ env.CLI_BUILD }}

      - name: Lint
        run: ${{ env.CLI_LINT }}

      - name: Get cypress cache directory path
        id: cypress-cache-dir
        run: echo "CYPRESS_BIN_PATH=$(npx cypress cache path)" >> $GITHUB_ENV

      - name: Upload build cache
        uses: actions/cache@v3
        with:
          path: ./*
          key: build-cache-${{ github.sha }}

      - name: Upload cypress binary cache
        uses: actions/cache@v3
        if: ${{ env.CYPRESS_BIN_PATH != ''}}
        with:
          path: ${{ env.CYPRESS_BIN_PATH }}
          key: cypress-${{ runner.os }}
          restore-keys: cypress-${{ runner.os }}

      # - name: Run unit tests
      #   run: ${{ env.CLI_TEST_UNIT }}

      # - name: Update semantic version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GHA_PAT_PRIVATE || secrets.GHA_PAT || secrets.GITHUB_TOKEN }}
      #   run: ${{ env.CLI_VERSION }}

      # - name: Packr
      #   if: ${{ inputs.packr_command != '' }}
      #   run: ${{ env.CLI_PACKR }}

      # - name: Upload build artifacts
      #   if: ${{ inputs.build_artifact_folder != ''}}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ inputs.build_artifact_name }}
      #     path: ${{ inputs.build_artifact_folder }}
      #     retention-days: 1
      #     if-no-files-found: error

      # - name: Upload unit test coverage artifacts
      #   if: ${{ inputs.coverage_artifact_folder != ''}}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ inputs.coverage_artifact_name }}
      #     path: ${{ inputs.coverage_artifact_folder }}
      #     retention-days: 1
