name: Build
on:
  workflow_call:
    inputs:
      package_manager:
        required: false
        type: string
        default: 'yarn'
      build_command:
        required: false
        type: string
        default: 'build'
      lint_command:
        required: false
        type: string
        default: 'lint'
      node_version:
        required: false
        type: string
        default: 'latest'
      cypress_bin_path:
        required: false
        type: string
        default: '~/.cache/Cypress'

jobs:
  labeler:
    name: Label branch
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compile:
    name: Compile source
    runs-on: ubuntu-latest
    env:
      CLI_INSTALL:
      CLI_BUILD:
      CLI_LINT:
      LOCK_FILE:
    steps:
      - name: Create environment variables for yarn commands
        if: inputs.package_manager == 'yarn'
        run: |
          echo "CLI_INSTALL=yarn install --frozen-lockfile" >> $GITHUB_ENV
          echo "CLI_BUILD=yarn ${{ inputs.build_command }}" >> $GITHUB_ENV
          echo "CLI_LINT=yarn ${{ inputs.lint_command }}" >> $GITHUB_ENV
          echo "LOCK_FILE=yarn.lock" >> $GITHUB_ENV

      - name: Create environment variables for npm commands
        if: inputs.package_manager == 'npm'
        run: |
          echo "CLI_INSTALL=npm ci" >> $GITHUB_ENV
          echo "CLI_BUILD=npm run ${{ inputs.build_command }}" >> $GITHUB_ENV
          echo "CLI_LINT=npm run ${{ inputs.lint_command }}" >> $GITHUB_ENV
          echo "LOCK_FILE=package-lock.json" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: ${{ inputs.package_manager }}

      - name: Configure github internal package repo access
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=$PACKAGE_TOKEN" > .npmrc
          echo "@flexbase-eng:registry=https://npm.pkg.github.com" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Retrieve dependencies cache
        id: dependencies-cache
        env:
          FILE_HASH: ${{ hashFiles(env.LOCK_FILE) }}
        uses: actions/cache/restore@v3
        with:
          path: ./node_modules
          key: node-modules-${{ runner.os }}-${{ env.FILE_HASH }}

      - name: Install dependencies
        if: steps.dependencies-cache.outputs.cache-hit != 'true'
        run: ${{ env.CLI_INSTALL }}

      - name: Compile
        run: ${{ env.CLI_BUILD }}

      - name: Lint
        run: ${{ env.CLI_LINT }}

      - name: Update dependencies cache
        uses: actions/cache@v3
        env:
          FILE_HASH: ${{ hashFiles(env.LOCK_FILE) }}
        with:
          path: ./node_modules
          key: node-modules-${{ runner.os }}-${{ env.FILE_HASH }}

      - name: Upload build cache
        uses: actions/cache@v3
        with:
          path: ./*
          key: build-cache-${{ github.sha }}

      - name: Upload cypress binary cache
        uses: actions/cache@v3
        if: ${{ inputs.cypress_bin_path != '' }}
        with:
          path: ${{ inputs.cypress_bin_path }}
          key: cypress-${{ runner.os }}
          restore-keys: cypress-${{ runner.os }}
