name: Netlify Deploy
on:
  workflow_call:
    inputs:
      build_artifact_name:
        required: false
        type: string
        default: dist
      build_artifact_folder:
        required: false
        type: string
        default: dist
      is_alias:
        required: false
        type: boolean
        default: true
      environment:
        required: true
        type: string
    outputs:
      netlify_output:
        description: Netlify json output
        value: ${{ jobs.deploy.outputs.netlify_output}}
      netlify_deploy_url:
        description: Netlify deploy url
        value: ${{ jobs.deploy.outputs.netlify_deploy_url }}
      netlify_prod_url:
        description: Netlify production url
        value: ${{ jobs.deploy.outputs.netlify_prod_url }}
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  NETLIFY_PROD:
  NETLIFY_ALIAS:

jobs:
  deploy:
    name: Netlify Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      netlify_output: ${{ steps.netlify_deploy.outputs.netlify_output }}
      netlify_deploy_url: ${{ steps.netlify_deploy.outputs.netlify_deploy_url }}
      netlify_prod_url: ${{ steps.netlify_deploy.outputs.netlify_prod_url }}
    steps:
      - if: inputs.is_alias != true
        run: echo "NETLIFY_PROD=--prod" >> $GITHUB_ENV

      - name: Retrieve build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.build_artifact_name }}
          path: ${{ inputs.build_artifact_folder }}

      - name: Look up netlify alias
        uses: peter-evans/find-comment@v2
        id: lookup
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: 'Deployed to'
          comment-author: 'github-actions[bot]'

      - if: steps.lookup.outputs.comment-id == 0
        run: echo ${{steps.lookup.outputs.comment-body}} | sed -n 's/.*https:\/\/\(.*\)--.*/NETLIFY_ALIAS=--alias \1/p' >> $GITHUB_ENV

      - name: Deploy to Netlify
        id: netlify_deploy
        uses: flexbase-eng/actions/netlify-cli@main
        with:
          args: deploy --dir=${{ inputs.build_artifact_folder }} ${{ env.NETLIFY_PROD }} ${{ env.NETLIFY_ALIAS}}
        timeout-minutes: 2

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: edumserrano/find-create-or-update-comment@v1
        env:
          DEPLOY_URL: ${{ steps.netlify_deploy.outputs.netlify_deploy_url }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: 'Deployed to'
          comment-author: 'github-actions[bot]'
          body: 'Deployed to ${{ env.DEPLOY_URL }}'
          edit-mode: replace
