name: Netlify Deploy
on:
  workflow_call:
    inputs:
      netlify_site_id:
        required: true
        type: string
      build_artifact_download:
        required: false
        type: string
        default: dist
      build_artifact_download_path:
        required: true
        type: string
      package_manager:
        required: false
        type: string
        default: yarn
      is_prod:
        required: false
        type: boolean
        default: false
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NETLIFY_SITE_ID: ${{ inputs.netlify_site_id}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - if: inputs.is_prod == true
        run: echo "NETLIFY_PROD=--prod" >> $GITHUB_ENV

      - name: Retrieve build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.build_artifact_download }}
          path: ${{ inputs.build_artifact_download_path }}

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=${{ inputs.build_artifact_download_path }} ${{ env.NETLIFY_PROD }}
        timeout-minutes: 1
