name: Deploy web app to Netlify
on:
  workflow_call:
    inputs:
      netlify_site_id:
        required: true
        type: string
      build_artifact_download:
        required: true
        type: string
        default: dist
      build_artifact_download_path:
        required: true
        type: string
        default: dist
      package_manager:
        required: false
        type: string
        default: yarn
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        # pull down compiled build artifact to build_artifact_download_path locally
        - uses: actions/download-artifact@v3
          with:
            name: ${{ inputs.build_artifact_download }}
            path: ${{ inputs.build_artifact_download_path }}
        # deploy artifact
        - name: Deploy to Netlify
          uses: nwtgck/actions-netlify@v1.2
          with:
            publish-dir: ${{ inputs.build_artifact_download_path }}
            production-branch: main
            deploy-message: "Deploy from GitHub Actions"
            enable-pull-request-comment: true
            enable-commit-comment: true
            overwrites-pull-request-comment: true
          timeout-minutes: 1
