name: Chromatic build and deploy
on:
  workflow_call:
    inputs:
      chromatic_command:
        required: false
        type: string
        default: 'build:storybook'

jobs:
  deploy:
    name: Chromatic build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: ./*
          key: build-cache-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: Run chromatic
        id: chromatic_deploy
        uses: chromaui/action@v1
        env:
          CI: true
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: ${{ inputs.chromatic_command }}
          skip: ${{ github.event.pull_request.draft == true }}
          exitOnceUploaded: true
        timeout-minutes: 2

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: edumserrano/find-create-or-update-comment@v1
        env:
          DEPLOY_URL: ${{ steps.chromatic_deploy.outputs.storybookUrl }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: 'Storybook deployed to'
          comment-author: 'github-actions[bot]'
          body: 'Storybook deployed to ${{ env.DEPLOY_URL }}'
          edit-mode: replace
