name: Production Release Slack Notification
on:
  workflow_call:
    inputs:
      gha_deployment_failure_url:
        required: true
        type: string
      production_url:
        required: false
        type: string
        default: https://www.flexbase.app
      release_title:
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  FAILURE_URL: ${{ inputs.gha_deployment_failure_url }}
  PRODUCTION_URL: ${{ inputs.production_url }}
  RELEASE_TITLE: ${{ inputs.release_title || github.event.repository.name }}

permissions:
  contents: read

jobs:
  prod-notify:
    runs-on: ubuntu-latest
    steps:
       - name: Get commits
         uses: octokit/request-action@v2.x
         id: get_commit_list
         with:
           route: GET /repos/{owner}/{repo}/commits
           owner: ${{ github.repository_owner }}
           repo: ${{ github.event.repository.name }}
      
      - name: Post Success to a Slack channel
        if: ${{ success() }}
        id: slack-success
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":rocket: ${{ env.RELEASE_TITLE }} has been shipped to production. Commit info and links are below :rocket:"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Author*: ${{ fromJSON(steps.get_commit_list.outputs.data)[0].commit.author.name }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Description*: ${{ fromJSON(steps.get_commit_list.outputs.data)[0].commit.message }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Commit Details*: ${{ fromJSON(steps.get_commit_list.outputs.data)[0].html_url }}"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
      - name: Post Failure to a Slack channel
        if: ${{ failure() }}
        id: slack-failure
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "There was an issue shipping ${{ github.event.repository.name }} to production."
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": <${{ env.FAILURE_URL }}|production deployment logs>"
                  }
                }
              ]
            }
