name: End to end tests
on:
  workflow_call:
    inputs:
      package_manager:
        required: false
        type: string
        default: 'yarn'
      test_command:
        required: false
        type: string
        default: 'test:e2e:ci'
      coverage_artifact_folder:
        required: false
        type: string
        default: 'coverage/lcov.info'
      coverage_artifact_name:
        required: false
        type: string
        default: 'code-coverage-report'
      cypress_bin_path:
        required: false
        type: string
        default: '~/.cache/Cypress'
      base_url:
        required: true
        type: string

env:
  CLI_TEST: yarn ${{ inputs.test_command }}
  CURRENTS_PROJECT_ID: ${{ secrets.CYPRESS_CLOUD_PROJECT_ID }}
  CURRENTS_RECORD_KEY: ${{ secrets.CYPRESS_CLOUD_KEY }}
  CURRENTS_BUILD_ID: ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}
  BASE_URL: ${{ inputs.base_url }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create environment variables for npm commands
        if: inputs.package_manager == 'npm'
        run: echo "CLI_TEST=npm run ${{ inputs.test_command }}" >> $GITHUB_ENV

      - name: Retrieve build cache
        uses: actions/cache/restore@v3
        with:
          path: ./*
          key: build-cache-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: Retrieve cypress binary cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ inputs.cypress_bin_path }}
          key: cypress-${{ runner.os }}
          fail-on-cache-miss: true

      - name: Run tests
        run: ${{ env.CLI_TEST }} --ci-build-id ${{ env.CURRENTS_BUILD_ID }} --config baseUrl=${{ env.BASE_URL }}
        timeout-minutes: 5

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 1        