name: NPM Publish
on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        default: latest
    secrets:
      NPM_TOKEN:
        required: true

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
        
    - name: Retrieve build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        registry-url: 'https://registry.npmjs.org'
        always-auth: true
        node-version: latest
        cache: 'yarn'

    - name: Setup yarn
      run: yarn install --frozen-lockfile

    - name: Publish
      run: yarn publish --access public --tag ${{ inputs.tag }}
