name: NPM Publish
on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
  pull_request:
  push:
    branches: [ $default-branch ]

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
        
    - name: Retrieve build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Publish
      run: |
        if [ -z "${{ inputs.tag }}"]
        then
          yarn publish
        else
          yarn publish --tag ${{ inputs.tag }}
        fi
