name: Build
on:
  workflow_call:
    inputs:
      package_folder:
        required: false
        type: string
      use_packr:
        required: false
        type: boolean
        default: true
      major_version:
        required: false
        type: string
      minor_version:
        required: false
        type: string
      revision:
        required: false
        type: string

env:
  PACKR_MAJOR_VERSION: 
  PACKR_MINOR_VERSION: 
  PACKR_REVISION: 

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-lint-test-packr:
    name: Build/Lint/Test/Packr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting
    
    - name: "Check file existence for yarn"
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "yarn-lock.json"
      
    - uses: actions/setup-node@v3
      if: steps.check_files.outputs.files_exists == 'true'
      with:
        node-version: latest
        cache: 'yarn'

    - uses: actions/setup-node@v3
      if: steps.check_files.outputs.files_exists == 'false'
      with:
        node-version: latest
        cache: 'npm'

    - name: Build major version env
      if: ${{ inputs.major_version != ''}}
      run: echo 'PACKR_MAJOR_VERSION=--major ${{ inputs.major_version }}' >> $GITHUB_ENV

    - name: Build minor version env
      if: ${{ inputs.minor_version != ''}}
      run: echo 'PACKR_MINOR_VERSION=--minor ${{ inputs.minor_version }}' >> $GITHUB_ENV

    - name: Build revision env
      if: ${{ inputs.revision != ''}}
      run: echo 'PACKR_REVISION=--revision ${{ inputs.revision }}' >> $GITHUB_ENV

    - name: Install yarn
      if: steps.check_files.outputs.files_exists == 'true'
      run: yarn install --frozen-lockfile

    - name: Build yarn
      if: steps.check_files.outputs.files_exists == 'true'
      run: yarn build

    - name: Lint yarn
      if: steps.check_files.outputs.files_exists == 'true'
      run: yarn lint

    - name: Test yarn
      if: steps.check_files.outputs.files_exists == 'true'
      run: yarn test   

    - name: Install npm
      if: steps.check_files.outputs.files_exists == 'false'
      run: npm install --ci

    - name: Build npm
      if: steps.check_files.outputs.files_exists == 'false'
      run: npm run build

    - name: Lint npm
      if: steps.check_files.outputs.files_exists == 'false'
      run: npm run lint

    - name: Test npm
      if: steps.check_files.outputs.files_exists == 'false'
      run: npm run test    

    - name: Packr
      if: ${{ inputs.use_packr == true }}
      run: yarn packr ${{ env.PACKR_MAJOR_VERSION }} ${{ env.PACKR_MINOR_VERSION }} ${{ env.PACKR_REVISION }}

    - name: Store build artifacts
      if: ${{ inputs.package_folder != ''}}
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ inputs.package_folder }}
        retention-days: 1

    - name: Store coverage artifacts
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage/lcov.info
        retention-days: 1
