name: Build
on:
  workflow_call:
    inputs:
      package_folder:
        required: false
        type: string
        default: 'dist'
  pull_request:
  push:
    branches: [ $default-branch ]

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting
    - uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'yarn'

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test

    - name: Pack
      run: yarn pack

    - name: Store build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ inputs.package_folder }}
        retention-days: 1

    - name: Store coverage artifacts
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage/lcov.info
        retention-days: 1