name: SonarCloud
on:
  workflow_call:
    inputs:
      project_key:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

env:
  SONAR_ORG: flexbase
  SONAR_PROJECT_KEY: ${{ inputs.project_key }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  sonarcloud:
    name: Sonarcloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Retrieve coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@vmaster
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
