name: Build
on:
  workflow_call:
    inputs:
      package_folder:
        required: false
        type: string
        default: 'dist'
      use_packr:
        required: false
        type: boolean
        default: true
      major_version:
        required: false
      minor_version:
        required: false
      revision:
        required: false
  pull_request:
  push:
    branches: [ $default-branch ]

env:
  PACKR_MAJOR_VERSION: ${{ inputs.major_version }}
  PACKR_MINOR_VERSION: ${{ inputs.minor_version }}
  PACKR_REVISION: ${{ inputs.revision }}

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting
    - uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'yarn'

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test

    - name: Build major version env
      if: ${{ env.PACKR_MAJOR_VERSION != ''}}
      run: echo 'PACKR_MAJOR_VERSION=--major $PACKR_MAJOR_VERSION' >> $GITHUB_ENV

    - name: Build minor version env
      if: ${{ env.PACKR_MINOR_VERSION != ''}}
      run: echo 'PACKR_MINOR_VERSION=--major $PACKR_MINOR_VERSION' >> $GITHUB_ENV

    - name: Build revision env
      if: ${{ env.PACKR_REVISION != ''}}
      run: echo 'PACKR_REVISION=--major $PACKR_REVISION' >> $GITHUB_ENV

    - name: Packr
      if: ${{ inputs.use_packr == true }}
      run: yarn packr ${{ env.PACKR_MAJOR_VERSION }} ${{ env.PACKR_MINOR_VERSION }} ${{ env.PACKR_REVISION }}

    - name: Store build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ inputs.package_folder }}
        retention-days: 1

    - name: Store coverage artifacts
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage/lcov.info
        retention-days: 1